-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#111412',
  base01 = '#0c0f0d',
  base02 = '#191c1a',
  base03 = '#404942',
  base04 = '#c0c9c0',
  base05 = '#e1e3de',
  base06 = '#2e312e',
  base07 = '#373a37',

  base08 = '#ffb4ab',
  base09 = '#ffbac1',
  base0A = '#b5ccba',
  base0B = '#a0d9b3',
  base0C = '#e89ca4',
  base0D = '#85bd99',
  base0E = '#394e40',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#85bd99',
  fg = '#111412',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#45151d',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#ffbac1',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#b5ccba',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#33694a',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#0c0f0d',
  fg = '#a0d9b3',
})
